# statestore.yaml for Azure Blob storage component
# componentType: state.azure.blobstorage
# version: v1
# metadata:
#   - name: accountName
#     value: nicksstatestore
#   - name: containerName
#     value: mycontainer
#   - name: azureClientId
#     value: 07cc4076-2b6f-45e5-9737-ca5711afaf03

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"